[package]
name = "rtree"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
glob = "0.3.1"
ignore = "0.4.23"
indicatif = "0.17.8"
rayon = "1.10.0"
structopt = "0.3.26"
